catalyst_report_stock_summary:
    path: /stock
    defaults: { _controller: CatalystReportBundle:InventoryStock:index }

catalyst_report_stock_csv:
    path: /stock/csv
    defaults: { _controller: CatalystReportBundle:InventoryStock:csv }
    
catalyst_report_stock_print:
    path: /stock/print
    defaults: { _controller: CatalystReportBundle:InventoryStock:print }  
    
        
catalyst_report_compare_summary:
    path: /comparative
    defaults: { _controller: CatalystReportBundle:Comparative:index }

catalyst_report_compare_csv:
    path: /comparative/csv
    defaults: { _controller: CatalystReportBundle:Comparative:csv }
    
catalyst_report_compare_print:
    path: /comparative/print
    defaults: { _controller: CatalystReportBundle:Comparative:print }    
    
    
catalyst_report_damaged_summary:
    path: /damaged
    defaults: { _controller: CatalystReportBundle:Damaged:index }
    
catalyst_report_damaged_csv:
    path: /damaged/csv
    defaults: { _controller: CatalystReportBundle:Damaged:csv }
    
catalyst_report_damaged_print:
    path: /damaged/print
    defaults: { _controller: CatalystReportBundle:Damaged:print }       
    
    
catalyst_report_po_summary:
    path: /posummary
    defaults: { _controller: CatalystReportBundle:Po:index }

catalyst_report_po_csv:
    path: /posummary/csv
    defaults: { _controller: CatalystReportBundle:Po:csv }
    
catalyst_report_po_print:
    path: /posummary/print
    defaults: { _controller: CatalystReportBundle:Po:print }    
    
    
catalyst_report_prcadjust_summary:
    path: /prcadjust
    defaults: { _controller: CatalystReportBundle:Adjust:index }
    
catalyst_report_prcadjust_csv:
    path: /prcadjust/csv
    defaults: { _controller: CatalystReportBundle:Adjust:csv }
    
catalyst_report_prcadjust_print:
    path: /prcadjust/print
    defaults: { _controller: CatalystReportBundle:Adjust:print }    
    
    
catalyst_report_dr_summary:
    path: /drsummary
    defaults: { _controller: CatalystReportBundle:Dr:index }
    
catalyst_report_dr_print:
    path: /drsummary/print
    defaults: { _controller: CatalystReportBundle:Dr:print }

catalyst_report_dr_csv:
    path: /drsummary/csv
    defaults: { _controller: CatalystReportBundle:Dr:csv }   
    
    
catalyst_report_returned_summary:
    path: /returnedsummary
    defaults: { _controller: CatalystReportBundle:Returned:index }
    
catalyst_report_returned_print:
    path: /returnedsummary/print
    defaults: { _controller: CatalystReportBundle:Returned:print }

catalyst_report_returned_csv:
    path: /returnedsummary/csv
    defaults: { _controller: CatalystReportBundle:Returned:csv }


catalyst_report_balance_summary:
    path: /balancesummary
    defaults: { _controller: CatalystReportBundle:Balance:index }

catalyst_report_balance_print:
    path: /balancesummary/print
    defaults: { _controller: CatalystReportBundle:Balance:print }


catalyst_report_balance_csv:
    path: /balancesummary/csv
    defaults: { _controller: CatalystReportBundle:Balance:csv }


catalyst_report_insufficient_summary:
    path: /insufficient
    defaults: { _controller: CatalystReportBundle:Insufficient:index }


catalyst_report_prodfreq_summary:
    path: /prodfrequency
    defaults: { _controller: CatalystReportBundle:Frequency:index }


catalyst_report_po_pdf:
    path: /pdf
    defaults: { _controller: CatalystReportBundle:Po:report }
