menu_items:
    - id: gist_accounting_menu
      acl: gist_accounting.menu
      label: Accounting
      icon: fa-money


    - id: gist_accounting_settings
      acl: gist_accounting_settings.menu
      label: Accounting Settings
      parent: gist_accounting_menu

    - id: gist_accounting_main_index
      acl: gist_accounting_main.menu
      label: Main Accounts
      parent: gist_accounting_settings

    - id: gist_accounting_accounts_index
      acl: gist_accounting_accounts.menu
      label: Chart of Accounts
      parent: gist_accounting_settings

    - id: gist_crj_settings_index
      acl: gist_crj_settings.menu
      label: CRJ Settings
      parent: gist_accounting_settings

    - id: gist_tb_settings_index
      acl: gist_tb_settings.menu
      label: Trial Balance Settings
      parent: gist_accounting_settings

    - id: gist_banks_menu
      acl: gist_banks.menu
      label: Banks
      parent: gist_accounting_menu
    - id: gist_accounting_banks_index
      acl: gist_accounting_banks.menu
      label: Bank
      parent: gist_banks_menu
    - id: gist_accounting_bank_accounts_index
      acl: gist_accounting_bank_accounts.menu
      label: Bank Accounts
      parent: gist_banks_menu


    - id: gist_terminals_menu
      acl: gist_terminals.menu
      label: Terminals
      parent: gist_accounting_menu
    - id: gist_terminals_terminal_index
      acl: gist_terminals_terminal.menu
      label: Terminal
      parent: gist_terminals_menu
    - id: gist_terminals_terminal_operator_index
      acl: gist_terminals_terminal_operator.menu
      label: Terminal Operator
      parent: gist_terminals_menu

    - id: menu_hr
      acl: hris_admin.menu
      label: Payroll Settings
      parent: gist_accounting_menu
    - id: hris_admin_basic_settings_index
      acl: hris_admin_basic_settings.menu
      label: Basic Settings
      parent: menu_hr
    - id: hris_admin_overtime_matrix_index
      acl: hris_admin_overtime_matrix.menu
      label: Overtime Matrix
      parent: menu_hr
    - id: hris_admin_night_differential_matrix_index
      acl: hris_admin_night_differential_matrix.menu
      label: Night Differential Matrix
      parent: menu_hr
    - id: hris_admin_benefit_index
      acl: hris_admin_benefit.menu
      label: Benefit
      parent: menu_hr
#    - id: hris_admin_schedules_index
#      acl: hris_admin_schedules.menu
#      label: Employee Time Schedule
#      parent: menu_hr
    - id: hris_admin_events_index
      acl: hris_admin_events.menu
      label: Events & Holidays
      parent: menu_hr
    - id: hris_admin_leave_type_index
      acl: hris_admin_leave_type.menu
      label: Leaves
      parent: menu_hr
    - id: hris_admin_tax_matrix_index
      acl: hris_admin_tax_matrix.menu
      label: Tax Matrix
      parent: menu_hr

    - id: hris_payroll_settings_bonus_index
      acl: hris_payroll_settings_bonus.menu
      label: Bonus
      parent: menu_hr
    - id: hris_payroll_settings_fines_index
      acl: hris_payroll_settings_fines.menu
      label: Fines
      parent: menu_hr
    - id: hris_payroll_settings_deposit_index
      acl: hris_payroll_settings_deposit.menu
      label: Deposit
      parent: menu_hr
    - id: hris_payroll_settings_incentive_index
      acl: hris_payroll_settings_incentive.menu
      label: Incentives
      parent: menu_hr

    - id: gist_accounting_cdj_index
      acl: gist_accounting_cdj.menu
      label: CDJ
      parent: gist_accounting_menu

    - id: gist_accounting_crj_index
      acl: gist_accounting_crj.menu
      label: CRJ
      parent: gist_accounting_menu

    - id: gist_accounting_general_index
      acl: gist_accounting_general.menu
      label: General Journal
      parent: gist_accounting_menu

    - id: gist_accounting_tb_index
      acl: gist_accounting_tb.menu
      label: Trial Balance
      parent: gist_accounting_menu
      