
gist_accounting_tb_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:TrialBalance:index }

gist_accounting_tb_generate:
    pattern: /list
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:TrialBalance:generateCSV }

gist_accounting_crj_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:TrialBalance:grid }

gist_accounting_tb_csv:
    pattern: /csv
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:TrialBalance:csv }

gist_tb_settings_index:
    pattern: /settings
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:TrialBalanceSettings:index }

gist_tb_settings_save:
    pattern: /settings
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:TrialBalanceSettings:save }
