menu_items:
    - id: menu_tools
      acl: hris_tools.menu
      label: Tools
      icon: fa-file-o
    # - id: hris_report_form_index
    #   acl: hris_report_leaves.menu
    #   label: Leaves
    #   parent: menu_report
    - id: hris_tools_manager
      acl: hris_tools_schedule.menu
      label: Manager
      parent: menu_tools
    - id: hris_tools_office
      acl: hris_tools_schedule.menu
      label: Office
      parent: menu_tools
    - id: hris_tools_schedule_index
      acl: hris_tools_schedule.menu
      label: Schedule
      parent: hris_tools_manager
    - id: hris_tools_weekly_schedule_index
      acl: hris_tools_weekly_schedule.menu
      label: Weekly Schedule
      parent: hris_tools_manager

    - id: hris_tools_schedule_index2
      acl: hris_tools_schedule.menu
      label: Attendance Today
      parent: hris_tools_manager
    - id: hris_tools_schedule_index2
      acl: hris_tools_schedule.menu
      label: Resolution Center
      parent: hris_tools_manager

    - id: hris_tools_bonus_index
      acl: hris_tools_bonus.menu
      label: Bonus/Fines
      parent: menu_tools
    - id: hris_tools_deposit_index
      acl: hris_tools_deposit.menu
      label: Deposit
      parent: menu_tools
    - id: hris_tools_adjustment_index
      acl: hris_tools_adjustment.menu
      label: Adjustment
      parent: menu_tools
    - id: hris_tools_advance_index
      acl: hris_tools_advance.menu
      label: Cash Advance
      parent: menu_tools
    - id: hris_tools_xz_index
      acl: hris_tools_xz.menu
      label: X/Z Reports
      parent: menu_tools