
hris_tools_advance_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:CashAdvance:index }

hris_tools_advance_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:CashAdvance:grid }

hris_tools_advance_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:CashAdvance:addForm }

hris_tools_advance_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: HrisToolsBundle:CashAdvance:addSubmit }

hris_tools_advance_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:CashAdvance:editForm }

hris_tools_advance_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: HrisToolsBundle:CashAdvance:editSubmit }

hris_tools_advance_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:CashAdvance:delete }


